### ISSUE TITLE
Where can I find the answer?

### ISSUE THREAD

**Issue by AStogov** [hczhcz/puzzle#2]
I cannot find it anywhere =_=

**Comment by hczhcz** [comment]
There is no published answer. Just try to solve the puzzles or do a brute force cracking :-)

**Comment by hczhcz** [comment]
Feel free to ask questions about some levels. I will try to guess what I was thinking 2 years ago.

**Comment by AStogov** [comment]
level 9, decode "6368706f69"
i stuck here...

**Comment by hczhcz** [comment]
It is "63 68 70 6f 69". Guess what would happen then.. XD

**Comment by AStogov** [comment]
oh, i got it!
thanks!
